-- Player: each user of PowerBAN
CREATE TABLE players (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Wallet: deposit accounts derived from the master seed
CREATE TABLE wallets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    account_index BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE, -- index in seed derivation
    ban_address TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    last_claimed_at TIMESTAMPTZ
);

-- Draw: one per daily PowerBAN draw
CREATE TABLE draws (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    draw_date DATE NOT NULL UNIQUE,   -- 1/day
    jackpot INTEGER,
    entropy_tx_hash TEXT,    -- tx hash used as randomness seed
    winning_numbers INTEGER[], -- array of 5 numbers [1-35]
    winners INTEGER,
    status TEXT NOT NULL CHECK (status IN ('scheduled', 'in_progress', 'completed')),
    created_at TIMESTAMPTZ DEFAULT now(),
    completed_at TIMESTAMPTZ
);

-- Ticket: one purchase = one row, with chosen 5 numbers
CREATE TABLE tickets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    draw_id UUID NOT NULL REFERENCES draws(id) ON DELETE CASCADE,
    numbers INTEGER[5] NOT NULL,
    purchase_tx_hash TEXT,
    win_address TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Winner: link tickets to their prize for a draw
CREATE TABLE winners (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticket_id UUID NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    draw_id UUID NOT NULL REFERENCES draws(id) ON DELETE CASCADE,
    prize_amount_raw NUMERIC NOT NULL,   -- store in raw units
    payout_tx_hash TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (ticket_id, draw_id)
);
